### ISSUE TITLE
Milestones view is broken

### ISSUE THREAD

**Issue by ad-si** [ZenHubIO/support#1375]
When I open `https://app.zenhub.com/workspace/o/<org>/<repo>/milestones` the list is empty and I get following error:

```
Possibly unhandled o@https://app.zenhub.com/dist/vendor.e5e3aab3bca36b2c430f.js:47:89156
then/</</<@https://app.zenhub.com/dist/index.43c4334c42fb019b580d.js:35:7717
a@https://app.zenhub.com/dist/index.43c4334c42fb019b580d.js:35:6341
add@https://app.zenhub.com/dist/index.43c4334c42fb019b580d.js:35:6652
then/</<@https://app.zenhub.com/dist/index.43c4334c42fb019b580d.js:35:7689
each@https://app.zenhub.com/dist/index.43c4334c42fb019b580d.js:15:13512
then/<@https://app.zenhub.com/dist/index.43c4334c42fb019b580d.js:35:7626
Deferred@https://app.zenhub.com/dist/index.43c4334c42fb019b580d.js:35:8221
then@https://app.zenhub.com/dist/index.43c4334c42fb019b580d.js:35:7602
a@https://app.zenhub.com/dist/vendor.e5e3aab3bca36b2c430f.js:47:89341
i@https://app.zenhub.com/dist/vendor.e5e3aab3bca36b2c430f.js:47:88878
e.exports/e.prototype._settlePromiseFromHandler@https://app.zenhub.com/dist/vendor.e5e3aab3bca36b2c430f.js:47:64419
e.exports/e.prototype._settlePromiseAt@https://app.zenhub.com/dist/vendor.e5e3aab3bca36b2c430f.js:47:66478
e.exports/e.prototype._settlePromises@https://app.zenhub.com/dist/vendor.e5e3aab3bca36b2c430f.js:47:68703
e.exports/e.prototype._rejectPromises@https://app.zenhub.com/dist/vendor.e5e3aab3bca36b2c430f.js:47:68572
r.prototype._consumeFunctionBuffer@https://app.zenhub.com/dist/vendor.e5e3aab3bca36b2c430f.js:18:125559
r/this.consumeFunctionBuffer@https://app.zenhub.com/dist/vendor.e5e3aab3bca36b2c430f.js:18:124931
c.prototype.run@https://app.zenhub.com/dist/vendor.e5e3aab3bca36b2c430f.js:18:66377
s@https://app.zenhub.com/dist/vendor.e5e3aab3bca36b2c430f.js:18:65885
 2 vendor.e5e3aab3bca36b2c430f.js:47:43162
```

**Comment by azenMatt** [comment]
Hi @ad-si - could you also share a screenshot of your network tab when this error is thrown? do you get any 'red' errors in that section? 

cc @Mathieuu

**Comment by ad-si** [comment]
The https://api.zenhub.io/v4/workspaces/<id>/open-milestones endpoint returns `{"message":"Error response from GitHub API"}`

One of the accounts associated with the organization got currently suspended.
Maybe you're still trying to use it to access organization level data?

**Comment by Mathieuu** [comment]
Hi @ad-si, thanks for reporting the error. 
> Maybe you're still trying to use it to access organization level data?
That might be the reason.

Could you send to support@zenhub.com including:
- the organization and the repository name from which you access the open milestones page.
- and the repo_id from the url you just indicated above: https://api.zenhub.io/v4/workspaces/**repo_id**/open-milestones (with the repo_id)

That would allow us  to look it up into our logs and see what happened.

**Comment by ad-si** [comment]
I sent you an email with the details!

**Comment by Mathieuu** [comment]
Can you try again? We flushed the cache for this repo. This should fix it. 

Also, could you log out from the extension through the ZenHub badge at the top left corner of your browser and login again.

**Comment by ad-si** [comment]
Mh, it didn't work 😕. I tried hard reloading and deleting all cookies, but it didn't help either.
Still the same error message.
(I'm currently not using the extension, so this is no problem)

**Comment by ad-si** [comment]
Hi, are there any news on this? It is still broken ☹️

**Comment by tjwallace** [comment]
Sorry @ad-si, we needed to flush a few more caches - it should be working now. Let us know how it goes.

**Comment by ad-si** [comment]
Yes, now it's working. Thanks a lot!

**Comment by gtpark** [comment]
I'm having the same problem in the GitHub Enterprise version. 
A recent major change is the conversion of the owner of the repo.
What is the cause of this problem and how does it work?

@tjwallace, @Mathieuu
