### ISSUE TITLE
New issues take a while to show up on the board

### ISSUE THREAD

**Issue by kyspy** [ZenHubIO/support#286]
When I make a new issue, the card takes a few minutes to show up in the board view.

**Comment by aupright** [comment]
Hi @kyspy thanks for reaching out!

Are you still noticing this problem when creating new issues? 

A few of us here noticed a similar problem last week, and it seems to have cleared up since. If there still seems to be a delay here, please let us know and we can trouble shoot further!

**Comment by kyspy** [comment]
Hi Aaron,

Thanks for the update. I am still noticing the problem when creating new
issues. The new issue shows up immediately in the task view, but not in the
board view. I've tried refreshing the page but it still takes about a
minute for the issue to show up in the board view.

**Comment by aupright** [comment]
Thanks for the follow up @kyspy!

I'm issuing this one up internally so that we can take a closer look into why this might be happening. I'll make sure to update this thread here as soon as I have more info and try my best to give you an eta around a hotfix!

**Comment by Mottie** [comment]
Any news on this? I've noticed this problem recently as well.

When I open the boards after a day or so, I notice only one issue. I hit the reload button and after the boards refresh I see the new issues. This gif shows that, but it might be hard to tell:

![zenhub](https://cloud.githubusercontent.com/assets/136959/8825524/78b6ded6-3045-11e5-93a0-d53aaa53e570.gif)

**Comment by kyspy** [comment]
It seems to be working again for me as well. Thanks for following up!

**Comment by Mottie** [comment]
Working? Or, not working? It's not updating on initialization for me.

**Comment by kyspy** [comment]
It was working for me a couple of days ago. Will check again today when I
get to the office.

**Comment by kyspy** [comment]
It's currently not working.

**Comment by azenMatt** [comment]
thanks for the follow ups @Mottie @kyspy - continuing our investigation....

**Comment by azenMatt** [comment]
How long is the current lag for adding the new issues? 

worst case scenario, it shouldn't be more than 5-10 seconds, are you experiencing more?

**Comment by Mottie** [comment]
In my case, if I open the boards even a day after a new issue is opened, it won't show up until after I reload the boards page. The new issues don't show up initially.

**Comment by kyspy** [comment]
The number of issues updates immediately: 
<img width="278" alt="2015-07-25 at 11 12 am" src="https://cloud.githubusercontent.com/assets/3890285/8890690/a7a0d0d2-32be-11e5-880e-17b485b22f68.png">

However, in my case the issue just isn't showing up on the board view after 6+ minutes and multiple browser refreshed. I tried clearing my browser catch and it's still not showing up. It is showing up immediately in the issues list view.

**Comment by azenMatt** [comment]
Just an update on this one - we are still working on making these issues appear faster on the board - with the goal that they are immediate!

**Comment by azenMatt** [comment]
@kyspy @Mottie 

How is this looking for you both now? 

We just did another round of improvements and the issues are appearing much faster for me - with no reload required. I hope it is the same for you?

**Comment by Mottie** [comment]
I haven't opened the boards in over a week... I just now opened it and I can see issues opened from 3 days ago; but issues opened about 36 hours ago and newer are no where to be found, at least on initial load. This includes closed issues.

If I reload the boards the newer issues show up.

**Comment by kyspy** [comment]
I am still experiencing the delay where new issues do not appear on the
board.

**Comment by RodneyTurnham** [comment]
I had not seen this when I created #546. Maybe the same, or a related issue?

**Comment by azenMatt** [comment]
Likely related - we have some updates in the pipeline that will improve the speed of new issues being added that should solve this for everyone. 

However, please let me know if you are consistently getting this where they do not show up after a refresh/a couple of mins. That really shouldn't happen! 

If you see it again, please feel free to reach out directly to support@zenhub.io and we can dig deeper on what might be causing it.

**Comment by RodneyTurnham** [comment]
@azenMatt wrote "In the very worst case scenario, if these issues did not get picked up in the cache - it should completely reset after one hour. If you find that the issues are still not appearing after that, please let me know!"

OK, 5 days later and this issue is still not showing on the board view. Letting you know :grinning: In the last 5 days, Macbook has been completely shut down and restarted. Suggestions gratefully welcomed!

**Comment by RodneyTurnham** [comment]
Additional info: just added two new issues, one each, to two boards. On one board, the new issue displayed immediately ... didn't even need to refresh the page. On the other, new issue is not showing up. This is the _same_ board where a previously-entered issue hasn't displayed after 5 days.

Could it be something in the settings for that particular board?

**Comment by azenMatt** [comment]
Thanks for the update @RodneyTurnham 

Last night we released 2.5.10 - this contained some updates to how we reconnect a board after a disconnection event occurred. It looks like your symptoms match this problem. 

Would you be able to check that you are on v2.5.10 and see if these issues are now on your board?

**Comment by RodneyTurnham** [comment]
@azenMatt : my installation says "2.15.10" ... don't know how I could be ahead of you, but that's what it says! I updated all extensions ... version number didn't change. New issues are still not showing up on this board, and on one other. Poking around a bit, I found two issue numbers which don't show up on either the open or closed issues lists. The first of these DOES show up on the Boards view! The two issues I'm having a problem with are the first two created after these. Could this be part of the problem?

**Comment by azenMatt** [comment]
Hi @RodneyTurnham - are you having better luck with this now? 

We have pushed some more changes that should make sure that issues always show up. 

We do still have one 'gotcha' that we are working on - sometimes new issues show up in a random place in the first pipeline, which is very confusing if you scroll to the bottom and expect to see your issue! 

We are still working on getting rid of that one! 

If you still have some issues that are in your GitHub issue list but are not on the board, if you can let me know the org/repo name I can manually clear that board cache for you and that should flush everything through.

**Comment by RodneyTurnham** [comment]
@azenMatt  Sorry to be the bearer of bad news, but the two repositories where the issues aren't showing up on the board are unchanged ... still not showing the new issues.

Not sure if you can clear the board cache for private repos, but here they are:
https://github.com/tma1/diana
https://github.com/tma1/informer

I'll let you know if anything changes with these. Thanks for looking into it for us.

**Comment by azenMatt** [comment]
Thanks @RodneyTurnham - we just cleared the cache for both of those. 

I want to make sure we can get to a root cause for you here - if/when this happens again, would you be able to jump onto a screenshare and one of our developers can see if they can get to the bottom of it? If you can email support@zenhub.io I can answer there. 


In terms of the initial problem here, I will close this issue and lets move follow ups to email :smile:

**Comment by RodneyTurnham** [comment]
@azenMatt: It appears that clearing the cache on these repos resolved the issue. Thanks!

**Comment by matthewcornell** [comment]
Hi. I am also experiencing this problem. When you say "clearing the cache" I assume you mean the browser cache. I've done so on Mac 10.13 > Firefox 56.0.2 and Chrome 62.0.3202.94 and my new issues still do not show up. I have not waited an hour (which, you have to admit, is unreasonable when you're trying to move a project ahead). Maybe I'm trying to add cards incorrectly. Here's what I did:

- On the issues page: create new issues 
- `is:issue is:open` shows 11 Open
- On the project page: click "Add Cards..." in the upper right
- I see three old, closed issues, and no open ones, including the new ones. Entering `is:issue is:open` in the search box shows "No results".

Please let me know what I can do to continue working in GitHub. Thank you.

**Comment by azenMatt** [comment]
> On the project page: click "Add Cards..." in the upper right

Hi @matthewcornell - can you confirm you are on the ZenHub 'boards' page? There shouldn't be an 'add cards' option anywhere as all the cards are automatically included. 

![image](https://user-images.githubusercontent.com/7584089/32917663-c9b693e0-cad4-11e7-9900-52d25e69a8af.png)

**Comment by matthewcornell** [comment]
I am embarrassed to say I thought I was on the main GitHub issues page. Please accept my apologies.

**Comment by azenMatt** [comment]
No worries - always nice to have an easy to resolve support question 🙌  😁
