### ISSUE TITLE
Tooltips are obscured in "Expanded" mode

### ISSUE THREAD

**Issue by junketjim** [ZenHubIO/support#569]
When the board is in expanded mode (and full screen), I cannot see the text on the tooltips for the filter buttons (show/hide open issues, pull requests, closed issues buttons)

![screen_shot_2016-02-01_at_13_27_38](https://cloud.githubusercontent.com/assets/2206147/12718637/da1af6b8-c8e7-11e5-8325-46d51a7185d7.png)

**Comment by junketjim** [comment]
I can see that on extension 2.15.20 this is fixed.  Thanks!

**Comment by robamaton** [comment]
I'm running 2.15.28, and this is still a problem, although it only happens after one of the right-most filters (open issues, PRs, closed issues) is toggled. @junketjim is this happening for you?

**Comment by azenMatt** [comment]
yes - it looks like when those buttons are not toggled, the tool tip is underneath. when they are toggled - it moves above 

We will get it fixed :)

**Comment by azenMatt** [comment]
Hi @junketjim - this is fixed in 2.15.47 :smile:
