### ISSUE TITLE
Labels not updating

### ISSUE THREAD

**Issue by talsafran** [ZenHubIO/support#638]
I recently did some label cleanup in our project and renamed bunch of labels: for example, `bug` is now capitalized to `Bug.`

For some reason though (caching?), many of my issues still appear with the old label:

![](https://dl.dropboxusercontent.com/spa/gcrmzi51hzw4tnm/soa335cf.png)

As you can see here, our project no longer has a lower case `bug` label, but it still appears in our Zenhub board.

![](https://dl.dropboxusercontent.com/spa/gcrmzi51hzw4tnm/qe5vlcvv.png)

Halp?

**Comment by azenMatt** [comment]
Hi @talsafran 

Good news today! We just released a fix for this :smile: 

If you can update to version 2.15.93, we now have an updated check that will keep all your labels in sync.

This means all labels will be correct when a board is first loaded, and if a change happens to a label elsewhere, it will be updated on the board within ~10 seconds.

Please try it out and let me know if you have any problems!

**Comment by aaronwest** [comment]
I've also experienced this issue over the past 2 weeks. I just checked and I'm on 2.15.95 and the issue is still apparent. In my case, the label changes weren't capitalization but more `label name` => `added text: label name`.

I've tried:

* restarting the browser
* shift + refresh
* updating ZenHub extension
* logging out of ZenHub / ZH Dashboard and back in

![zh](https://cloud.githubusercontent.com/assets/231569/14217122/dfdbbdd6-f811-11e5-951e-43401852ad13.png)
