### ISSUE TITLE
[bug] Clicking "Filter by this epic" clears any other already established filters

### ISSUE THREAD

**Issue by cbeams** [ZenHubIO/support#895]
I first started noticing this behavior within the last week, so I believe it is new.

Repro steps:

1. Set up a board with at least one milestone, say `v1.0.0` and at least one epic. Assign the epic to the `v1.0.0` milestone.
1. Filter the board by a milestone, say `v1.0.0`
1. Click "Filter by this epic" on the epic with the intention of further narrowing the current filter, i.e. "Filter the board for all v1.0.0 issues in this epic"
1. Notice that the `v1.0.0` milestone filter is eliminated and that only the epic filter remains.

Actual behavior: the milestone filter gets removed when the epic filter is added.

Expected behavior: both filters should remain in place.

Also notice that if one swaps steps 2 and 3 above, then both filters *do* remain in place as expected.

**Comment by azenMatt** [comment]
Hi @cbeams  - as you correctly suggested in #870 this is a bug we introduced when making sure the label filter for epic is removed when a epic filter is applied. 

We will get this fixed

**Comment by cbeams** [comment]
Just checking in on this as it continues to be a significant hindrance in my day-to-day workflow. Looks like it's now `In Progress` as of 5 days ago, which is a good sign. Any further updates? Thanks.

**Comment by azenMatt** [comment]
This is just going through code review at the moment - so should be live in the very near future

**Comment by azenMatt** [comment]
Hi @cbeams - this one is now live, so when filtering by an epic the only filter that will be removed is the label 'epic' (if applied) 

Let me know if you have any other issues with this!

**Comment by cbeams** [comment]
@azenMatt is there something I need to do on my side to ensure I have this latest fix? I've quit and reopened my browser, and walked through the same workflow as I originally detailed in the issue description. I see no change in behavior.

**Comment by azenMatt** [comment]
You may need to manually update your extension (sometimes the browser can be slow in pushing it out) 

Anything 2.24.13 and above this should be working on?

**Comment by cbeams** [comment]
I have verified that I have version 2.24.14. Unfortunately, I am still seeing the bad behavior as described below:

1. Filter by a given milestone, say v1.0.0.
2. Click 'Filter by this epic' on any epic still showing on the board.
3. Notice that the v1.0.0 filter disappears, and now only the epic filter remains.
4. Click 'Remove filter' on the same epic card as clicked in (2)
5. Notice that there are now no filters active.

Expected behavior is that these filters are additive. That the v1.0.0 milestone filter persists until I explicitly remove it. That when I add the epic filter, I see cards that are both scheduled for milestone v1.0.0 and part of the epic in question.

**Comment by azenMatt** [comment]
yes - you are right, sorry about that - reopening and refixing!

**Comment by azenMatt** [comment]
take two for this one on v2.24.18! 

Now the only filter that will be removed when you filter by an epic is 'label' = 'epic'

**Comment by cbeams** [comment]
@azenMatt I can confirm this fix is working for me. I've happily been using the hell out of it over the last 24 hours. Thanks!

**Comment by azenMatt** [comment]
Excellent :D
